version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
